version: '3.7'

volumes:
    loki: ~
    tempo: ~
    grafana: ~
    prometheus: ~

services:
    # The service below recursively changes the user ownership of the tempo-data volume's directories to the 1000 user. 
    # It is required for correct work of the Grafana Tempo. The command should be started once. Then the service can be deleted.
    volume-permissions:
        image: ubuntu:latest
        tty: true
        stdin_open: true
        user: "root"
        command: "chown -R 1000:1000 /mnt"
        volumes:
            - "tempo:/mnt/edge-tempo-data"
    loki:
        image: "grafana/loki:latest"
        hostname: logs
        command: -config.file=/etc/loki/local-config.yaml
        volumes:
            - loki:/loki
        ports:
            # - "3100:3100" # http and Grafana data source
            - "9095:9095" # grpc
    tempo:
        image: grafana/tempo:latest
        hostname: tempo
        user: "1000"
        restart: "unless-stopped"
        command: [ "-config.file=/etc/tempo.yaml" ]
        volumes:
            - ./config/tempo/tempo.yaml:/etc/tempo.yaml
            - tempo:/tmp/tempo
        ports:
            - "4317:4317"  # otlp grpc
            #- "3200:3200"  # native port for Grafana data source
        depends_on:
            - volume-permissions
    prometheus:
        image: prom/prometheus:latest
        hostname: prometheus
        volumes:
          - ./config/prometheus/:/etc/prometheus/
          - prometheus:/prometheus
        command:
          - '--config.file=/etc/prometheus/prometheus.yml'
          - '--storage.tsdb.path=/prometheus'
        ports:
          - 9090:9090 #UI and for Grafana data source
    grafana:
        image: grafana/grafana-oss:latest-ubuntu
        hostname: grafana
        ports: 
            - "3000:3000" #UI
        volumes:
            - grafana:/var/lib/grafana
            - ./config/grafana/provisioning:/etc/grafana/provisioning
        environment:
            - GF_AUTH_ANONYMOUS_ENABLED=true
            - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
            - GF_AUTH_DISABLE_LOGIN_FORM=true
        depends_on:
            - loki
            - tempo
            - prometheus