apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    editable: true
    isDefault: false
    url: "http://loki:3100"
    uid: loki
    jsonData:
      derivedFields:
        # Field with internal link pointing to data source in Grafana.
        # datasourceUid value can be anything, but it should be unique across all defined data source uids.
        - datasourceUid: edge_tempo
          matcherRegex: "(?:TraceId)=(\\w+)"
          name: TraceID
          # url will be interpreted as query for the datasource
          url: '$${__value.raw}'
          # optional for URL Label to set a custom display label for the link.
          urlDisplayLabel: 'View Trace'
